# fly.toml app configuration file generated for wandering-pond-503 on 2023-06-26T11:30:10-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-pond-503"
primary_region = "lax"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
